# For building the client platforms
FROM alpine:latest AS linux-client-android

# Install bash and java
RUN apk update
RUN apk add bash openjdk21
ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk
ENV PATH="$PATH:$JAVA_HOME/bin"

# Download Android SDK and set PATH
RUN mkdir -p /android-sdk/cmdline-tools
RUN mkdir -p /tmp
RUN wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O /tmp/commandlinetools.zip
RUN unzip /tmp/commandlinetools.zip -d /tmp && rm /tmp/commandlinetools.zip
RUN mv /tmp/cmdline-tools /android-sdk/cmdline-tools/latest/
ENV ANDROID_HOME="/android-sdk"
ENV PATH="$PATH:$ANDROID_HOME/cmdline-tools/latest/bin"

# Install platform-tools
RUN yes | sdkmanager "platform-tools"
ENV PATH="$PATH:$ANDROID_HOME/platform-tools"

FROM linux-client-android AS linux-client-cache

WORKDIR /source

COPY . /source

RUN ./gradlew --no-daemon :composeApp:dependencies

FROM linux-client-cache AS linux-client

VOLUME /output

RUN mv /source/entrypoint/entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
