# CURRENTLY NOT WORKING

FROM mcr.microsoft.com/windows:20H2 AS windows-client-android
ARG COMMAND_LINE_TOOLS_VERSION=11076708

# Install OpenJDK 21
RUN winget install -e --id Microsoft.OpenJDK.21
# Install wget
RUN winget install -e --id JernejSimoncic.Wget

# Create the required directories
RUN mkdir C:\\android-sdk\\cmdline-tools
RUN mkdir C:\\tmp

RUN wget https://dl.google.com/android/repository/commandlinetools-win-${COMMAND_LINE_TOOLS_VERSION}_latest.zip -O C:\\tmp\\commandlinetools.zip
RUN tar -xf C:\\tmp\\commandlinetools.zip -C C:\\tmp && del C:\\tmp\\commandlinetools.zip
RUN mv C:\\tmp\\cmdline-tools C:\\android-sdk\\cmdline-tools\\latest

# Set the environment variables
ENV ANDROID_HOME="C:\\android-sdk"

# Install platform-tools
RUN yes | sdkmanager "platform-tools"
ENV PATH="$PATH:$ANDROID_HOME/platform-tools"

FROM windows-client-android AS windows-client-cache

WORKDIR "C:\\source"

COPY . "C:\\source"

RUN & "C:\\source\\gradlew.bat" --no-daemon :composeApp:dependencies

FROM windows-client-cache AS windows-client

VOLUME "C:\\output"

RUN mv C:\\source\\entrypoint\\entrypoint.bat C:\\entrypoint.bat

ENTRYPOINT ["C:\\entrypoint.bat"]
