VERSION_NAME=1.0.0
VERSION_MAC=$VERSION_NAME
VERSION_ANDROID=$VERSION_NAME.1
VERSION_ANDROID_CODE=1
VERSION_LIN=$VERSION_NAME~1
VERSION_LIN_RELEASE=1
VERSION_IOS=$VERSION_NAME
VERSION_WIN=$VERSION_NAME
