# Uncomment the next line to define a global platform for your project
# platform :ios, '16.6'

# See: https://kotlinlang.org/docs/multiplatform/compose-compatibility-and-versioning.html#supported-platforms
deployment_target = '15.6'

target 'iosApp' do
  use_frameworks!
  platform :ios, deployment_target
  pod 'composeApp', :path => '../composeApp'
end

post_install do |installer|
  installer.generated_projects.each do |project|
      project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
          end
      end
      project.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
      end
  end
end
