name: Release Binaries

on:
  release:

jobs:
  build-desktop:
    name: Build for Desktop
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Build
        env:
          BACKEND_HOST: ceaapp.escalaralcoiaicomtat.org
          BACKEND_PORT: 443
          BACKEND_HTTPS: true
        run: ./gradlew :composeApp:packageReleaseDistributionForCurrentOS

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            composeApp/build/compose/binaries/main-release/**/*.dmg
            composeApp/build/compose/binaries/main-release/**/*.msi
            composeApp/build/compose/binaries/main-release/**/*.deb
