name: Build and Publish

on:
  push:
    branches:
      - master
    paths:
      - "server/**"
      - "shared/**"
      - "gradle/**"
  release:
    types:
      - released

permissions:
  checks: write
  pull-requests: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Build and publish release
        if: ${{ github.event_name == 'release' }}
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          VERSION: ${{ github.event.release.tag_name }}
        run: ./gradlew server:publishImage
      - name: Build and publish development
        if: ${{ github.event_name == 'release' }}
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: ./gradlew server:publishImage
