name: Release Binaries

on:
  release:

jobs:
  update-version-name:
    name: Update version name
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Update version name
        run: python ./composeApp/scripts/updateVersionName.py --name=${{ github.event.release.name }}

      - name: Increase version code
        id: increase_version_code
        run: python ./composeApp/scripts/increaseVersionCode.py

      - name: Commit modified version code file
        id: commit_version_code
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Updated Version'
          file_pattern: 'composeApp/version.txt composeApp/code.txt iosApp/iosApp.xcodeproj/project.pbxproj iosApp/iosApp/Info.plist'
          branch: master

  build-windows:
    name: Build for Windows
    runs-on: windows-latest

    needs: update-version-name
    if: always()

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      # Refresh version name just in case
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Update version name
        run: python ./composeApp/scripts/updateVersionName.py --name=${{ github.event.release.name }}

      - name: Package distribution
        run: ./gradlew --no-daemon :composeApp:packageDistributionForCurrentOS

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            composeApp/build/compose/binaries/**/org.centrexcursionistalcoi.app-${{ github.event.release.name }}*.exe

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest

    needs: update-version-name
    if: always()

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      # Refresh version name just in case
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Update version name
        run: python ./composeApp/scripts/updateVersionName.py --name=${{ github.event.release.name }}

      - name: Package distribution
        run: ./gradlew --no-daemon :composeApp:packageDistributionForCurrentOS

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            composeApp/build/compose/binaries/**/org.centrexcursionistalcoi.app_${{ github.event.release.name }}*.deb

  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    needs: update-version-name
    if: always()

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Import Keystore
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" > keystore.base64
          base64 --decode keystore.base64 > ./composeApp/keystore.jks

      - name: Import Google Services JSON
        env:
          GOOGLE_SERVICES_BASE64: ${{ secrets.GOOGLE_SERVICES_BASE64 }}
        run: |
          echo "$GOOGLE_SERVICES_BASE64" > google-services.base64
          base64 --decode google-services.base64 > ./composeApp/google-services.json

      # Refresh version name just in case
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Update version name
        run: python ./composeApp/scripts/updateVersionName.py --name=${{ github.event.release.name }}

      - name: Build release APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: ./gradlew --no-daemon :composeApp:assembleRelease :composeApp:bundleRelease

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            composeApp/build/outputs/**/*.apk
