name: Build and Publish Docker Compiler

on:
  push:
    branches:
      - master
    paths:
      - "build-compiler.yml"
      - "Dockerfile-*"
      - "entrypoint/*"

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push development
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile-${{ matrix.os }}
          push: true
          tags: arnyminerz/cea-app:compiler-${{ matrix.os }}
