name: Build and Push Server

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-server.yml'
      - 'server/**'
      - '*.gradle.kts'
      - '*.properties'
      - 'gradle/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish_docker_image:
    name: Build and Publish Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push development
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: arnyminerz/cea-app:development
          file: server/Dockerfile
